const ACTION = {
  CHANGE: "CHANGE",
  START: "START",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SET_DATA: "SET_DATA",
  REFETCH: "REFETCH",
  RESET_ACTION: "RESET_ACTION",
  RESET_STATE: "RESET_STATE",
  RESET_LIST: "RESET_LIST",
  RESET_DATA: "RESET_DATA",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
};

export { ACTION };
